complexity:
  LongParameterList:
    active: false
  LongMethod:
    ignoreAnnotated: [ 'Composable' ]
  ComplexCondition:
    threshold: 7

formatting:
  Filename:
    active: false

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: [ 'preview' ]
  ReturnCount:
    active: false

naming:
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9_]*'
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  MatchingDeclarationName:
    active: false