complexity:
  LongParameterList:
    ignoreDefaultParameters: true
  LongMethod:
    ignoreAnnotated: [ 'Composable' ]

formatting:
  Filename:
    active: false

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: [ 'preview' ]

naming:
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9_]*'
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  MatchingDeclarationName:
    active: false