package com.yjy.core.designsystem.theme

import androidx.compose.ui.graphics.Color

internal val brandLight = Color(0xFFFF9E44)
internal val onBrandLight = Color(0xFFFFFFFF)
internal val brandBrightLight = Color(0xFFFFDFBA)
internal val onBrandBrightLight = Color(0xFF1D1813)
internal val brandDimLight = Color(0xFFFF881A)
internal val onBrandDimLight = Color(0xFFFFFFFF)
internal val backgroundLight = Color(0xFFF4F4F4)
internal val onBackgroundLight = Color(0xFF000000)
internal val onBackgroundMutedLight = Color(0xFF666666)
internal val surfaceLight = Color(0xFFFFFFFF)
internal val onSurfaceLight = Color(0xFF000000)
internal val onSurfaceMutedLight = Color(0xFF969696)
internal val dividerLight = Color(0xFFE6E6E6)
internal val disableLight = Color(0xFFADADAD)
internal val onDisableLight = Color(0xFFFFFFFF)
internal val onSnackbarLight = Color(0xFFFFFFFF)
internal val snackbarLight = Color(0xFF323232)

internal val brandDark = Color(0xFFFF9E44)
internal val onBrandDark = Color(0xFF000000)
internal val brandBrightDark = Color(0xFFFFBF84)
internal val onBrandBrightDark = Color(0xFF000000)
internal val brandDimDark = Color(0xFFFF9E44)
internal val onBrandDimDark = Color(0xFF000000)
internal val backgroundDark = Color(0xFF373737)
internal val onBackgroundDark = Color(0xFFFFFFFF)
internal val onBackgroundMutedDark = Color(0xFF9F9F9F)
internal val surfaceDark = Color(0xFF575757)
internal val onSurfaceDark = Color(0xFFFFFFFF)
internal val onSurfaceMutedDark = Color(0xFFB7B7B7)
internal val dividerDark = Color(0xFF474747)
internal val disableDark = Color(0xFFADADAD)
internal val onDisableDark = Color(0xFF000000)
internal val onSnackbarDark = Color(0xFF000000)
internal val snackbarDark = Color(0xFFD1D1D1)

internal val kakaoBrand = Color(0xFFFEE500)
internal val googleBrand = Color(0xFFFFFFFF)
internal val naverBrand = Color(0xFF03C75A)